export const SUPPORTED_NETWORKS = [
    {
      name: "Moonbase Alpha",
      short_name: "moonbase",
      chain: "Moonbase",
      network: "testnet",
      chain_id: 1287,
      network_id: 1287,
      rpc_url: "https://rpc.api.moonbase.moonbeam.network",
      native_currency: {
        symbol: "DEV",
        name: "DEV",
        decimals: "18",
        contractAddress: "",
        balance: "",
      },
    },
    // {
    //   name: "Moonbeam",
    //   short_name: "moonbeam",
    //   chain: "Moonbeam",
    //   network: "mainnet",
    //   chain_id: 1284,
    //   network_id: 1284,
    //   rpc_url: "https://rpc.api.moonbeam.network",
    //   native_currency: {
    //     symbol: "GLMR",
    //     name: "Glimmer",
    //     decimals: "18",
    //     contractAddress: "",
    //     balance: "",
    //   },
    // },
    // {
    //   name: "Moonriver",
    //   short_name: "moonriver",
    //   chain: "Moonriver",
    //   network: "mainnet",
    //   chain_id: 1285,
    //   network_id: 1285,
    //   rpc_url: "https://rpc.moonriver.moonbeam.network",
    //   native_currency: {
    //     symbol: "MOVR",
    //     name: "Moonriver",
    //     decimals: "18",
    //     contractAddress: "",
    //     balance: "",
    //   },
    // },
  ]